name: Survey-Gen
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/app/src
      - ./nodemon.json:/app/nodemon.json
    ports:
      - 80:3000
    depends_on: 
      postgres:
        condition: service_healthy
        restart: true
        required: true
    env_file:
      - ./.env
    command: npm run dev
  postgres:
    image: postgres:18
    restart: always
    shm_size: 128mb
    volumes:
      - db:/var/lib/postgres/data
    ports:
      - 5432:5432
    env_file:
      - ./.env
    # environment:
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  nodeModules:
  db: