version: "3"
name: Survey-Gen
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/app/src
      - ./nodemon.json:/app/nodemon.json
    ports:
      - 80:3000
    depends_on: 
      db:
        condition: service_healthy
        restart: true
        required: true
    env_file:
      - ./.env
    command: npm run dev
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: william
      POSTGRES_DB: survey-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d survey-db -U william"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  nodeModules: