

type AuthPayload {
  token: String!
  user: User!
}

type Mutation {
  signup(args: SignupInput!): AuthPayload!
  signin(args: SigninInput!): AuthPayload!
}

input SignupInput {
  email: String! @constraint(format: "email", maxLength: 255)
  firstname: String @constraint(pattern: "^[0-9a-zA-Z]*$", maxLength: 255, minLength: 3)
  lastname: String @constraint(pattern: "^[0-9a-zA-Z]*$", maxLength: 255, minLength: 3)
  isPremium: Boolean!
  password: String!
    @constraint(
      pattern: "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$"
      maxLength: 30
      minLength: 8
    )
  confirmPassword: String!
}

input SigninInput {
  email: String!
  password: String!
}