scalar UUID
scalar Date

enum Order {
  ASC
  DESC
}

type GenericResponse {
  success: Boolean!
  message: String!
}

type DeleteResponse {
  success: Boolean!
  Message: String!
}

type PageInfo {
  startCursor: String
  endCursor: String
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
}

input PaginationInput {
  first: Int
  last: Int
  before: String
  after: String
}


input BooleanFilterInput{
  equals: Boolean
}

input IdFilterInput {
  equals: ID
  in: [ID!]
  not: ID
  notIn: [ID!]
}

input IntFilterInput {
    equals: Int
    gt: Int
    gte: Int
    in: [Int!]
    lt: Int
    lte: Int
    not: Int
    notIn: [Int!]
}

input StringFilterInput {
  contains: String
  endsWith: String
  equals: String
  in: [String!]
  not: String
  notIn: [String!]
  startsWith: String
}


input DateFilterInput {
    equals: Date
    gt: Date
    gte: Date
    lt: Date
    lte: Date
}