scalar UUID
scalar Timestamp

enum Order {
  ASC
  DESC
}

type DeleteResponse {
  success: Boolean!
  Message: String!
}

type PageInfo {
  startCursor: String
  endCursor: String
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
}

input PaginationInput {
  first: Int
  last: Int
  before: String
  after: String
}

type Cursor {
  createdAt: Timestamp!
  id: UUID!
}
