scalar UUID
scalar Date

enum Order {
  ASC
  DESC
}

type DeleteResponse {
  success: Boolean!
  Message: String!
}

type PageInfo {
  startCursor: String
  endCursor: String
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
}

input PaginationInput {
  first: Int
  last: Int
  before: String
  after: String
}

# type Cursor {
#   createdAt: Date!
#   id: UUID!
# }

input BooleanFilterInput{
    equals: Boolean
}

input IdFilterInput {
  equals: ID
  in: [ID!]
  not: IdFilterInput
  notIn: [ID!]
}

input IntFilterInput {
    equals: Int
    gt: Int
    gte: Int
    in: [Int!]
    lt: Int
    lte: Int
    not: IntFilterInput
    notIn: [Int!]
}

input StringFilterInput {
  contains: String
  endsWith: String
  equals: String
  in: [String!]
  # mode: QueryModeg
  not: NestedStringFilterInput
  notIn: [String!]
  startsWith: String
}

input NestedStringFilterInput {
  contains: String
  endsWith: String
  equals: String
  in: [String!]
  not: NestedStringFilterInput
  notIn: [String!]
  startsWith: String
}

input DateFilterInput {
    equals: Date
    gt: Date
    gte: Date
    in: [Date!]
    lt: Date
    lte: Date
    not: DateFilterInput
    notIn: [Date!]
}