scalar Date

type Survey {
  id: UUID!
  name: String!
  description: String!
  isPublic: Boolean!
  startDate: Date
  endDate: Date
  owner: User!
  createdAt: Date!
  updatedAt: Date!
  candidates(args: UserFilterInput!): UserConnection!
}

type SurveyEdge {
  cursor: String!
  node: Survey!
}

type SurveyConnection {
  totalCount: Int!
  edges: [SurveyEdge!]!
  pageInfo: PageInfo!
}


type Query {
  survey(id: UUID!): Survey
  surveys(args: SurveyFilterInput!): SurveyConnection!
}

type Mutation {
  createSurvey(args: CreateSurveyInput!): Survey!
  updateSurvey(args: UpdateSurveyInput!): Survey!
  deleteSurvey(id: UUID!): DeleteResponse!
  assignCandidates(args: UpdateCandidatesInput!): Survey!
  revokeCandidates(args: UpdateCandidatesInput!): Survey!
}

input UpdateCandidatesInput {
  surveyId: UUID!
  ids: [UUID!]!
}

input CreateSurveyInput {
  name: String!
  description: String!
  isPublic: Boolean!
  startDate: Date
  endDate: Date
}

input UpdateSurveyInput {
  id: UUID!
  name: String
  description: String
  isPublic: Boolean
  startDate: Date
  endDate: Date
}


input SurveyFilter {
  id: UUID
  description: StringFilterInput
  name: StringFilterInput
  isPublic: BooleanFilterInput
  createdAt: DateFilterInput
  updatedAt: DateFilterInput
  startDate: DateFilterInput
  endDate: DateFilterInput
}

input SurveyFilterInput {
  filters: SurveyFilter
  pagination: PaginationInput
}