scalar UUID
scalar Date

type Survey {
  id: UUID!
}

type User {
  id: UUID!
  email: String!
  firstname: String
  lastname: String
  isPremium: Boolean!
  surveys(data: SurveyFilterInput!): SurveyConnection!
  assignedSurveys(data: SurveyFilterInput!): SurveyConnection!
  answers(data: AnswersFilterInput!): SurveyConnection!
  createdAt: Date!
  updatedAt: Date!
}

type UserEdge {
  cursor: String!
  node: User!
}

type UserConnection {
  totalCount: Int!
  edges: [UserEdge!]!
  pageInfo: PageInfo!
}

type Query {
  user(id: UUID): User
  userByEmail(email: String!): User
  users(args: UserFilterInput!): UserConnection!
}

type Mutation {
  updateMe(args: UpdateUserInput!): User!
  deleteMe: DeleteResponse!
}

input UserFilter {
  id: UUID
  email: StringFilterInput
  firstname: StringFilterInput
  lastname: StringFilterInput
  isPremium: BooleanFilterInput
  createdAt: DateFilterInput
  updatedAt: DateFilterInput
}

input UserFilterInput {
  filters: UserFilter
  pagination: PaginationInput
}


input UpdateUserInput {
  email: String @constraint(format: "email", maxLength: 255)
  firstname: String @constraint(pattern: "^[a-zA-Zà-öø-ÿÀ-ÖØ-ß' -]{2,50}$", maxLength: 50, minLength: 2)
  lastname: String @constraint(pattern: "^[a-zA-Zà-öø-ÿÀ-ÖØ-ß' -]{2,50}$", maxLength: 50, minLength: 2)
  isPremium: Boolean
}
